enum Role {
  Admin
  Lead
  Intervenor
}

type Employee {
  id: PositiveInt!
  firstname: String!
  lastname: String!
  email: EmailAddress!
  password: String!
  role: Role!
  tickets: [Ticket!]!
  created_at: DateTime!
  updated_at: DateTime
}

input EmployeeInput {
  firstname: String!
  lastname: String!
  email: EmailAddress!
  password: String!
  role: Role!
}
