enum Status {
  Open
  Closed
  Underway
}

type Ticket {
  id: PositiveInt!
  title: String!
  content: String!
  status: Status!
  client_id: PositiveInt!
  client: Client
  created_at: DateTime!
  updated_at: DateTime
  messages: [Message]
  employees: [Employee]
}

input TicketInput {
  title: String!
  content: String!
  status: Status!
  client_id: PositiveInt!
}
